CREATE TABLE PERSONA (
    COD_PERSONA VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONTRASEÑA VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY (COD_PERSONA)
);

CREATE TABLE EMAIL (
    ID_EMAIL NUMBER(10) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    COD_PERSONA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_EMAIL PRIMARY KEY (ID_EMAIL),
    CONSTRAINT FK_EMAIL_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PERSONA(COD_PERSONA),
    CONSTRAINT UNQ_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE TELEFONO (
    ID_TELEFONO NUMBER(10) NOT NULL,
    FIJO VARCHAR2(12),
    MOVIL VARCHAR2(12) NOT NULL,
    COD_PERSONA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_TELEFONO PRIMARY KEY (ID_TELEFONO),
    CONSTRAINT FK_TELEFONO_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PERSONA(COD_PERSONA),
    CONSTRAINT UNQ_MOVIL UNIQUE (MOVIL)
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER(10) NOT NULL,
    COD_PERSONA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PERSONA(COD_PERSONA)
);

CREATE TABLE ORGANIZADOR (
    ID_ORGANIZADOR NUMBER(10) NOT NULL,
    NOMBRE_EVENTO VARCHAR2(50) NOT NULL,
    COD_PERSONA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_ORGANIZADOR PRIMARY KEY (ID_ORGANIZADOR),
    CONSTRAINT FK_ORGANIZADOR_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PERSONA(COD_PERSONA)
);

CREATE TABLE EVENTO (
    COD_EVENTO VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_ORGANIZADOR NUMBER(10) NOT NULL,
    CONSTRAINT PK_EVENTO PRIMARY KEY (COD_EVENTO),
    CONSTRAINT FK_EVENTO_ORGANIZADOR FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID_ORGANIZADOR),
    CONSTRAINT CK_FECHA CHECK (FECHA_INICIO < FECHA_FIN),
    CONSTRAINT UNQ_NOMBRE_EVENTO UNIQUE (NOMBRE)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER(10) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    COD_EVENTO VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT FK_CATEGORIA_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO(COD_EVENTO),
    CONSTRAINT CK_CATEGORIA CHECK (TIPO IN ('CONFERENCIA', 'TALLER','OTROS'))
);

CREATE TABLE UBICACION (
    ID_UBICACION NUMBER(10) NOT NULL,
    LUGAR VARCHAR2(50) NOT NULL,
    COD_EVENTO VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_UBICACION PRIMARY KEY (ID_UBICACION),
    CONSTRAINT FK_UBICACION_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO(COD_EVENTO),
    CONSTRAINT CK_UBICACION CHECK (LUGAR IN ('ONLINE', 'PRESENCIAL'))
);

CREATE TABLE INSCRIPCION (
    ID_USUARIO NUMBER(10) NOT NULL,
    COD_EVENTO VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_INSCRIPCION PRIMARY KEY (ID_USUARIO, COD_EVENTO),
    CONSTRAINT FK_INSCRIPCION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_INSCRIPCION_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO(COD_EVENTO)
);

